### ISSUE TITLE
[#02] 재무 데이터 수집

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#1]
### Task List 

- [x] 기존 버전 코드 분석
- [ ] 데이터 수집 테스트
- [ ] 함수 모듈화
- [ ] S3 디렉토리 패스 설정
- [ ] S3에 데이터 저장
- [ ] Lambda에 함수 저장

### 버그 리포트

1.
