### ISSUE TITLE
[#08] 스타트업 투자 데이터 수집 - 크롤링

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#10]
### Task List 

- [ ] 기존 버전 코드 분석
- [ ] 데이터 수집 테스트
- [ ] 함수 모듈화
- [ ] S3 디렉토리 패스 설정
- [ ] S3에 데이터 저장
- [ ] Lambda에 함수 저장

### 버그 리포트

1.
