### ISSUE TITLE
[#07] 거시 경제 지표 및 금융시장 지표 데이터 수집

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#12]
### Task List 

- [ ] 데이터 수집 테스트
- [ ] 함수 모듈화
- [ ] S3 디렉토리 패스 설정
- [ ] S3에 데이터 저장
- [ ] Lambda에 함수 저장

### 버그 리포트

1.
