### ISSUE TITLE
[#03] 시장 데이터 수집

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#13]
### Task List 

- [x] 데이터 수집 테스트
- [x] 함수 모듈화
- [x] S3 디렉토리 패스 설정
- [x] S3에 데이터 저장
- [ ] Lambda에 함수 저장

### 버그 리포트

1.
