### ISSUE TITLE
[#02] RDS 초기 데이터 적재

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#2]
### Task List 

- [x] 기존 버전 데이터 분석
- [x] 서비스에 필요한 데이터 분리 (ERD 및 테이블 참고)
- [x] 해당 데이터 RDS에 적재

### 버그 리포트

1.
