### ISSUE TITLE
[#01] 데이터 수집 파이프라인 설계

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#3]
### Task List 

- [x] 데이터 수집 파이프라인 설계
- [x] 데이터 수집 파이프라인 검토
- [x] Lambda PoC - 10월 9일 7시
- [x] Lambda Layer PoC - 10월 9일 7시
- [ ] 크롤링 Lambda 구축
    - [ ] 스타트업 투자 데이터 수집 : 주원 (리펙토링 후 합류)
    - [ ] 연봉 데이터 수집 : 병수
- [ ] API 호출 Lambda 구축
    - [ ] 재무 데이터 수집 : 중헌 (15일)
    - [ ] 시장 데이터 수집 : 종명 (19일)
    - [ ] 거시 경제 지표 및 금융시장 지표 데이터 수집 : 원철 (17일)
    - [ ] 기타 비재무 데이터 수집 : 
    - [ ] 채용공고 데이터 수집 : 준석 (16일)
    - [ ] 뉴스(비정형) 데이터 수집 : 준경 (19일)
- [ ] Event Bridge PoC
- [ ] 스케줄링 구체화
- [ ] 스케줄링 자동화 설정

### 버그 리포트

1.
