### ISSUE TITLE
[#04] 모델링 및 Pipeline 포함

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#4]
### Task List 

- [ ] 선행연구 조사
- [ ] proposer 작성
- [ ] 모델링
- [ ] 모델 생성
- [ ] Base Model 선정
- [ ] 기업 안정성 평가 모델 학습
- [ ] 기업 안정성 평가 모델 성능 평가
- [ ] S3에 모델 삽입
- [ ] 예측 기능 수행 Lambda를 Pipeline에 추가
- [ ] 예측값을 RDS에 저장

### 버그 리포트

1.
