### ISSUE TITLE
[#04] 기타 비재무 데이터 수집

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobadream_data#7]
### Task List 

- [x] 데이터 수집 테스트
- [x] 함수 모듈화
- [ ] S3 디렉토리 패스 설정
- [ ] S3에 데이터 저장
- [ ] Batch Workload 저장

### 버그 리포트

1.
